version: "3"
services:
    service:
        build: .
        volumes:
            - ./static_files:/project/static_files/
            - ./config.json:/project/config.json
        environment:
            - "PYTHONUNBUFFERED=1"
